/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackendOfflineAlert: typeof import('./src/components/BackendOfflineAlert.vue')['default']
    FileDropper: typeof import('./src/components/FileDropper.vue')['default']
    FlyweightLeaderboard: typeof import('./src/components/FlyweightLeaderboard.vue')['default']
    HeavyweightLeaderboard: typeof import('./src/components/HeavyweightLeaderboard.vue')['default']
    Leaderboard: typeof import('./src/components/Leaderboard.vue')['default']
    MediumweightLeaderboard: typeof import('./src/components/MediumweightLeaderboard.vue')['default']
    PrizeTable: typeof import('./src/components/PrizeTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TrackACompositionDoughnut: typeof import('./src/components/TrackACompositionDoughnut.vue')['default']
    TrackAVideo: typeof import('./src/components/TrackAVideo.vue')['default']
    TrackBVideo: typeof import('./src/components/TrackBVideo.vue')['default']
  }
}
